In [1]:
import numpy as np

In [2]:
m1 = np.array([[2,4],[6,8]])

In [3]:
print("Original Matrix: \n", m1)

Original Matrix: 
 [[2 4]
 [6 8]]


In [4]:
m1_eigen_w, m1_eigen_v = np.linalg.eig(m1)

In [5]:
print("Eigen Value: ",m1_eigen_w)
print("Eigen Vector: \n",m1_eigen_v)

Eigen Value:  [-0.74456265 10.74456265]
Eigen Vector: 
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [7]:
#3d array
m2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [8]:
m2 = m2.reshape(3,3)

In [9]:
m2_eigen_w, m2_eigen_v = np.linalg.eig(m2)

In [10]:
print("Eigen Value: ",m2_eigen_w)
print("Eigen Vector: \n",m2_eigen_v)

Eigen Value:  [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Eigen Vector: 
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [ ]:
##TENSORFLOW

In [11]:
import tensorflow as tf

In [12]:
tf_m1 = tf.random.uniform([2,2], minval = 3, maxval = 10, dtype = tf.float32, )
print("Original Matrix: \n", tf_m1)

Original Matrix: 
 tf.Tensor(
[[6.7365    6.1778545]
 [6.9476595 9.806448 ]], shape=(2, 2), dtype=float32)


In [13]:
tf_m1_value, tf_m1_vector = tf.linalg.eigh(tf_m1)

In [14]:
print("Eigen Value: ",tf_m1_value)
print("Eigen Vector: \n",tf_m1_vector)

Eigen Value:  tf.Tensor([ 1.1562705 15.386677 ], shape=(2,), dtype=float32)
Eigen Vector: 
 tf.Tensor(
[[-0.7796575 -0.6262062]
 [ 0.6262062 -0.7796575]], shape=(2, 2), dtype=float32)


In [ ]:
#3x3 matrix
tf_m2 = tf.random.uniform([3,3], minval = 3, maxval = 10, dtype = tf.float32)
print("Original Matrix: \n", tf_m2)

Original Matrix: 
 tf.Tensor(
[[4.993222  8.358919  9.58536  ]
 [5.455655  7.884194  8.30066  ]
 [5.0017214 6.6669483 8.975639 ]], shape=(3, 3), dtype=float32)


In [ ]:
tf_m2_value, tf_m2_vector = tf.linalg.eigh(tf_m2)

In [ ]:
print("Eigen Value: ",tf_m2_value)
print("Eigen Vector: \n",tf_m2_vector)

Eigen Value:  tf.Tensor([ 0.789685  2.056494 19.006872], shape=(3,), dtype=float32)
Eigen Vector: 
 tf.Tensor(
[[ 0.7684321  -0.4383226   0.466246  ]
 [-0.63796985 -0.46772555  0.6117412 ]
 [ 0.05006483  0.7675325   0.6390519 ]], shape=(3, 3), dtype=float32)


In [ ]:
#5x5 matrix

tf_m3 = tf.random.uniform([5,5], minval = 2, maxval = 10, dtype = tf.float32)
print("Original Matrix: \n", tf_m3)

Original Matrix: 
 tf.Tensor(
[[7.0563145 6.580291  5.052623  9.582944  6.9338865]
 [4.9615545 2.3200274 2.610917  6.656165  7.6865673]
 [8.97147   9.529992  3.7051086 3.5482435 5.2854433]
 [6.085931  9.815249  9.479506  8.000159  9.204856 ]
 [3.4144182 3.3231382 3.5407505 4.5128775 5.1407623]], shape=(5, 5), dtype=float32)


In [ ]:
tf_m3_value, tf_m3_vector = tf.linalg.eigh(tf_m3)
print("Eigen Value: ",tf_m3_value)
print("Eigen Vector: \n",tf_m3_vector)

Eigen Value:  tf.Tensor([-7.2520065 -4.051362   2.3842752  3.1361063 32.005356 ], shape=(5,), dtype=float32)
Eigen Vector: 
 tf.Tensor(
[[-0.25050664 -0.25250956  0.7894677   0.24443346  0.4364382 ]
 [-0.6610634   0.5067435  -0.32011747  0.09027556  0.44224557]
 [ 0.70203716  0.46725976  0.03621466  0.18987775  0.50144494]
 [ 0.08463974 -0.6761674  -0.49395153  0.02000381  0.53967154]
 [ 0.01488214  0.06257596  0.1701936  -0.9463873   0.26692334]], shape=(5, 5), dtype=float32)
